Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> Standalone build and plugin tests pass, but in-tree build fails:
> 
> ERROR: /home/user/git/gerrit/core/master/plugins/gc-conductor/BUILD:87:1: no such package '@jgit//jar': BUILD file not found in directory 'jar' of external repository @jgit and referenced by '//plugins/gc-conductor:gc-conductor__plugin_test_deps'                                                                                    
> 
> ERROR: Analysis of target '//plugins/gc-conductor:gc-conductor_tests' failed; build aborted: no such package '@jgit//jar': BUILD file not found in directory 'jar' of external repository @jgit

Replacing [1] "@jgit//jar" with [2] "//lib:jgit" in ./BUILD fixes the in-tree plugin build, since I16370e57. However that replacement breaks the standalone build of course.

Hence I'm trying to add jgit locally as a library, under this plugin, so that replacement works also for standalone. I'm thinking of doing that as I don't know how to conditionally depend on either [1] or [2] above, depending on the bazel build mode.

Patch-set: 1
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>